SELECT 'CREATE INDEX ' || USER || '.' || SUBSTR(A.TABLE_NAME || '_' || ORA_HASH(A.COLUMN_NAME), 1, 30) || ' ON ' || USER || '.' || A.TABLE_NAME || ' (' || A.COLUMN_NAME || ') TABLESPACE &1;'
FROM USER_TAB_COLUMNS A
WHERE
    (
		A.COLUMN_NAME = 'ID'
		OR A.COLUMN_NAME LIKE '%\_ID' ESCAPE '\'
	) AND (A.TABLE_NAME, A.COLUMN_NAME) NOT IN (
        SELECT B.TABLE_NAME, B.COLUMN_NAME
        FROM USER_IND_COLUMNS B
    ) AND A.TABLE_NAME NOT IN (
        SELECT D.VIEW_NAME FROM USER_VIEWS D
    )
ORDER BY 1;